version: "3.8"
services:
  genegraphics:
    build: 
      target: prod
    image: "genegraphics:prod"
    labels:
      - 'traefik.http.routers.genegraphics.rule=Host(`${HOST_PROD}`)'
    environment:
      - "NODE_ENV=production"
